version: "3.7"
services:
  prometheus-alertmanager:
    build: .
    image: homecentr/prometheus-alertmanager:local
    environment:
      ALERTMANAGER_ARGS: "--log.level=debug"
    volumes:
      - ./example:/config
    ports:
      - 9093:9093
    restart: unless-stopped